// <auto-generated />
using System;
using Ability_Drive_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ability_Drive_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250214163142_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ability_Drive_API.Models.BusSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableDisabledSeats")
                        .HasColumnType("int");

                    b.Property<int>("AvailableNormalSeats")
                        .HasColumnType("int");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsWheelchairAccessible")
                        .HasColumnType("bit");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalDisabledSeats")
                        .HasColumnType("int");

                    b.Property<int>("TotalNormalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BusSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableDisabledSeats = 2,
                            AvailableNormalSeats = 20,
                            BusNumber = "B101",
                            DepartureTime = new DateTime(2024, 1, 1, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            FromLocation = "City Center",
                            IsWheelchairAccessible = true,
                            ToLocation = "North Station",
                            TotalDisabledSeats = 2,
                            TotalNormalSeats = 20
                        },
                        new
                        {
                            Id = 2,
                            AvailableDisabledSeats = 3,
                            AvailableNormalSeats = 30,
                            BusNumber = "B102",
                            DepartureTime = new DateTime(2024, 2, 1, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            FromLocation = "East Station",
                            IsWheelchairAccessible = true,
                            ToLocation = "West Station",
                            TotalDisabledSeats = 3,
                            TotalNormalSeats = 30
                        },
                        new
                        {
                            Id = 3,
                            AvailableDisabledSeats = 2,
                            AvailableNormalSeats = 25,
                            BusNumber = "B103",
                            DepartureTime = new DateTime(2024, 3, 1, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            FromLocation = "South Station",
                            IsWheelchairAccessible = true,
                            ToLocation = "Central Station",
                            TotalDisabledSeats = 2,
                            TotalNormalSeats = 25
                        });
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastKnownLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.PrimitiveCollection<string>("PreferredLocations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("VehicleRegistration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            LastKnownLocation = "Cairo",
                            LicenseNumber = "DRV12345",
                            Name = "Alice Smith",
                            Password = "pass#123",
                            PhoneNumber = "01134896510",
                            PreferredLocations = "[\"Cairo\",\"Giza\",\"Alexandria\"]",
                            Rating = 4.8m,
                            VehicleRegistration = "ABC123",
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            LastKnownLocation = "Giza",
                            LicenseNumber = "DRV12345",
                            Name = "Ali Mohammed",
                            Password = "pass#123",
                            PhoneNumber = "01111111111",
                            PreferredLocations = "[\"6th October\",\"Helwan\",\"Nasr City\"]",
                            Rating = 4.8m,
                            VehicleRegistration = "ABC123",
                            VehicleType = "Sedan"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            LastKnownLocation = "Alexandria",
                            LicenseNumber = "DRV67890",
                            Name = "Sarah Johnson",
                            Password = "pass#789",
                            PhoneNumber = "0222333444",
                            PreferredLocations = "[\"Maadi\",\"Zamalek\",\"New Cairo\"]",
                            Rating = 4.9m,
                            VehicleRegistration = "XYZ789",
                            VehicleType = "SUV"
                        });
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("UserId");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 100m,
                            Destination = "Giza",
                            DriverId = 1,
                            PickupLocation = "Cairo",
                            RequestTime = new DateTime(2024, 1, 1, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 150m,
                            Destination = "Nasr City",
                            DriverId = 2,
                            PickupLocation = "Helwan",
                            RequestTime = new DateTime(2024, 2, 1, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cost = 200m,
                            Destination = "New Cairo",
                            DriverId = 3,
                            PickupLocation = "Maadi",
                            RequestTime = new DateTime(2024, 3, 1, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ongoing",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Ability_Drive_API.Models.SeatBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusScheduleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabledPassenger")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("SeatBookings");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "email@gmail.com",
                            FirstName = "John",
                            IsDisabled = false,
                            LastName = "Doe",
                            Password = "password123",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@gmail.com",
                            FirstName = "Jane",
                            IsDisabled = true,
                            LastName = "Smith",
                            Password = "password321",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.johnson@gmail.com",
                            FirstName = "Bob",
                            IsDisabled = false,
                            LastName = "Johnson",
                            Password = "password456",
                            PhoneNumber = "1122334455"
                        });
                });

            modelBuilder.Entity("Ability_Drive_API.Models.UserVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UsedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Ride", b =>
                {
                    b.HasOne("Ability_Drive_API.Models.Driver", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverId");

                    b.HasOne("Ability_Drive_API.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.SeatBooking", b =>
                {
                    b.HasOne("Ability_Drive_API.Models.BusSchedule", "BusSchedule")
                        .WithMany("SeatBookings")
                        .HasForeignKey("BusScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ability_Drive_API.Models.User", "User")
                        .WithMany("SeatBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.UserVoucher", b =>
                {
                    b.HasOne("Ability_Drive_API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ability_Drive_API.Models.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.BusSchedule", b =>
                {
                    b.Navigation("SeatBookings");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Driver", b =>
                {
                    b.Navigation("Rides");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.User", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("SeatBookings");
                });

            modelBuilder.Entity("Ability_Drive_API.Models.Voucher", b =>
                {
                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
